version: '3.3'

# volumes:
  # volume-mariadb:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o:    'bind'
  #     device: ${HOME}/data/mariadb
  # V_wordpress:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o:    'bind'
  #     device: ${HOME}/data/wordpress

services:

  mariadb:
    container_name: Maria_DB
    env_file: ./.env
    build: 
      context: ./requirements/mariadb
      args:
      - WORDPRESS_DB_NAME
      - MARIADB_ROOT_PASSWD
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    volumes: 
      - ${HOME}/data/mariadb:/var/lib/mysql
    networks:
      - Docker_Network
    restart: always

  ##############

  wordpress:
    container_name: Word_Press
    build: 
      context: ./requirements/wordpress
      args:
      -  WORDPRESS_DB_NAME
      -  WORDPRESS_DB_USER
      -  WORDPRESS_DB_PASSWORD
      -  WORDPRESS_DB_HOST
    env_file: .env
    volumes:
      - ${HOME}/data/wordpress:/var/www/html
    depends_on:
      - mariadb 
    networks:
      - Docker_Network
    restart: always

  ##############

  # nginx:
  #   container_name: Nginx
  #   build: ./requirements/nginx
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - Docker_Network
  #    restart: always

networks:
  Docker_Network:
    driver: bridge
